### ISSUE TITLE
Not working anymore._.

### ISSUE THREAD

**Issue by Dai-Son** [Sebastian09-09/Anigame-Sniper#2]
It used to work.. but not work anymore now
tried to debugged but can't find any issue in it._.

**Comment by Sebastian09-09** [comment]
working on it right now

**Comment by Dai-Son** [comment]
![A](https://user-images.githubusercontent.com/61372575/116779307-1e07fe00-aaa8-11eb-802f-a604efaf95ee.png)
I dont know what happen to my progame or something
it all works fine until last noon>_< i dont know what happen .-.

**Comment by Sebastian09-09** [comment]
> It used to work.. but not work anymore now
> tried to debugged but can't find any issue in it._.

so..
i figured it out 
and the thing is this cant be fixed 
discord no more allows users to check the details of an embed or any message 
hence , you cant see what the embed says and cant claim the cards :'|

will be working on a new version for a anigame sniper
edit:wont be a sniper would be a grinder*
